version: '3.8'
services:
  app:
    build: .
    image: controle:latest
    ports:
      - "8501:8501"
    volumes:
      - ./Banco_Dados:/app/Banco_Dados
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8501 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432:5432"
volumes:
  db_data:
